name = "ImageClipboard"
uuid = "6db54171-f50f-4661-a74f-bc514ef16cee"
authors = ["hyrodium <hyrodium@gmail.com> and contributors"]
version = "0.0.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[targets]
test = ["Test", "Images"]
